trigger: none
pr:
- master

variables:
- template: variables/common.yml
- name: manifest
  value: manifest.wcf.json
- name: _testCategory
  value: WCF
stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      buildMatrixType: platformVersionedOs
      customBuildLegGrouping: pr-build
